Models/LichSu.cs
using System;

namespace QuanLyThongTinBenBaiCho.Models
{
    public class LichSu
    {
        public int LichSuId { get; set; }
        public DateTime NgayDauGia { get; set; } = DateTime.Now;
        public float GiaTri { get; set; }
        public DateTime NgayBatDau { get; set; } = DateTime.Now;
        public DateTime NgayKetThuc { get; set; } = DateTime.Now;
        public string TenDonVi { get; set; }
        public int BenId { get; set; }
        public Ben Bens { get; set; }
    }
}

Controllers/LichSuController.cs
using QuanLyThongTinBenBaiCho.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace QuanLyThongTinBenBaiCho.Controllers
{
    public class LichSuController : Controller
    {
        public readonly DataContext _context;
        public LichSuController()
        {
            _context = new DataContext();
        }
        public ActionResult Index(int Id)
        {
            ViewBag.BenId = Id;
            var entity = _context.Bens.Where(x => x.BenId == Id).FirstOrDefault();
            ViewBag.Ten = entity.Ten;
            return View();
        }
        public ActionResult LoadTable(int Id)
        {
            var data = _context.LichSus.Where(x => x.BenId == Id).AsQueryable();
            return View(data.ToList());
        }
        [HttpGet]
        public ActionResult AddOrUpdate(int id = 0, int BenId = 0)
        {
            if (id == 0)
            {

                return View(new LichSu() { BenId = BenId });
            }
            else
            {
                var entity = _context.LichSus.Where(x => x.LichSuId == id).FirstOrDefault();
                if (entity == default(LichSu))
                    throw new Exception("Không tìm thấy dữ liệu");
                return View(entity);
            }
        }
        [HttpPost]
        public ActionResult AddOrUpdate(LichSu model)
        {
            try
            {
                if (model.LichSuId == 0)
                {
                    _context.LichSus.Add(model);
                    _context.SaveChanges();
                    return Json(new GenericMessageVM()
                    {
                        Status = true,
                        Message = $"Thêm thành công!",
                        MessageType = GenericMessage.success,
                        Data = model
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var entity = _context.LichSus.Where(x => x.LichSuId == model.LichSuId).FirstOrDefault();
                    if (entity == default(LichSu))
                        throw new Exception("Không tìm thấy dữ liệu.");
                    entity.NgayKetThuc = model.NgayKetThuc;
                    entity.NgayBatDau = model.NgayBatDau;
                    entity.NgayDauGia = model.NgayDauGia;
                    entity.GiaTri = model.GiaTri;
                    entity.TenDonVi = model.TenDonVi;

                    _context.SaveChanges();
                    return Json(new GenericMessageVM()
                    {
                        Status = true,
                        Message = $"Cập nhật thành công!",
                        MessageType = GenericMessage.success,
                        Data = model
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new GenericMessageVM()
                {
                    Status = false,
                    Message = $"{ex.Message}",
                    MessageType = GenericMessage.error
                }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var data = _context.LichSus.Where(x => x.LichSuId == id).FirstOrDefault();
                _context.LichSus.Remove(data);
                _context.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/LichSu/AddOrUpdate.cshtml
@model QuanLyThongTinBenBaiCho.Models.LichSu
@{
    Layout = null;
}
<div class="modal-content">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box" style="padding:10px 10px">
                <h4 class="page-title">Thông tin lịch sử đấu giá</h4>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    @using (@Html.BeginForm("AddOrUpdate", "LichSu", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @Html.HiddenFor(model => model.LichSuId)
                        @Html.HiddenFor(model => model.BenId)
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label" style="display: flex; flex-direction: column">Ngày đấu giá</label>
                                @Html.EditorFor(model => model.NgayDauGia, new { htmlAttributes = new { @id = "flatpickr01", @class = "form-control", style = "width: 100%" } })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label" style="display: flex; flex-direction: column">Ngày bắt đầu</label>
                                @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @id = "flatpickr01", @class = "form-control", style = "width: 100%" } })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label" style="display: flex; flex-direction: column">Ngày kết thúc</label>
                                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @id = "flatpickr01", @class = "form-control", style = "width: 100%" } })
                            </div>
                        </div>
                    </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Giá trị<span class="text-danger">*</span></label>
                                    @Html.EditorFor(model => model.GiaTri, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Tên đơn vị sử dụng<span class="text-danger">*</span></label>
                                    @Html.EditorFor(model => model.TenDonVi, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>
                        </div>
      
                        <div class="form-group text-right mb-0">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                            <button type="button" data-dismiss="modal" class="btn btn-secondary">Đóng</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    flatpickr("#flatpickr01", {
        dateFormat: "m/d/Y",
    })
</script>

Views/LichSu/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header class="page-title-bar">
    <div class="d-md-flex align-items-md-start">
        <h1 class="page-title mr-sm-auto"> Quản lý lịch sử của @ViewBag.Ten </h1>
        <div class="btn-toolbar">
            <button type="button" class="btn btn-light" onclick="Popup('@Url.Action("AddOrUpdate","LichSu", new { BenId = ViewBag.BenId})')"><i class="oi oi-plus"></i> <span class="ml-1">Thêm</span></button>
            <button type="button" class="btn btn-light" onclick="window.location.href='/Home'"><i class="fas fa-arrow-left"></i> <span class="ml-1">Trở về</span></button>
        </div>
    </div>
</header>
<div class="page-section">
    <div class="card card-fluid">
        <div class="card-body">
            <div class="form-group">
                @*<div class="input-group input-group-alt">
                        <div class="input-group-prepend">
                            <select id="trangthai" class="custom-select">
                                <option selected value="-1"> Trạng thái </option>
                                <option value="1"> Đã giao </option>
                                <option value="0"> Nền trống </option>
                            </select>
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="oi oi-magnifying-glass"></span></span>
                            </div>
                            <input id="tennen" type="text" class="form-control" placeholder="Tên nền">
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><span class="oi oi-magnifying-glass"></span></span>
                            </div>
                            <input id="tennguoimua" type="text" class="form-control" placeholder="Tên người mua">
                        </div>
                        <button onclick="SubmitSearch()" class="btn btn-primary">Tìm kiếm</button>
                    </div>*@
            </div>
            <div class="table-responsive" id="tableAjax">
                @{
                    Html.RenderAction("LoadTable", "LichSu", new { Id = ViewBag.BenId });
                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="clientContactEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document" id="modalcontent">
    </div>
</div>
<script>
    function SubmitForm(form) {
        post_url = $(form).attr("action");
        $.ajax({
        type: "POST",
        url: post_url,
        data: $(form).serialize(),
        success: function (data) {
            if (data.success) {
                $('#exampleModal').modal('toggle');
                $("#tableAjax").load("@Url.Action("LoadTable", "LichSu", new { Id = ViewBag.BenId })");
            } else {
                $('#exampleModal').modal('toggle');
                $("#tableAjax").load("@Url.Action("LoadTable", "LichSu", new { Id = ViewBag.BenId })");
                }
            }
        });
        return false;
    }
    function SubmitSearch() {
        $.ajax({
            type: "Get",
            url: "/LichSu/LoadTable",
            contentType: "html",
            success: function (response) {
                $('#tableAjax').html(response);
            }
        });
        return false;
    }
    function Popup(urlMem) {
        var url = urlMem;
        $.ajax({
            url: url,
            type: 'GET',
            success: function (response) {
                $('#modalcontent').html(response);
                $("#exampleModal").modal("show");
            },
            error: function (xhr, status) {
                alert(status);
            }
        });
    }
    function Delete(url) {
        $.ajax({
            type: "POST",
            url: url,
            success: function (data) {
                if (data.success) {
                   $("#tableAjax").load("@Url.Action("LoadTable", "LichSu", new { Id = ViewBag.BenId })");
                } else {
                   $("#tableAjax").load("@Url.Action("LoadTable", "LichSu", new { Id = ViewBag.BenId })");
                }
            }
        });
    }
</script>

Views/LichSu/LoadTable.cshtml
@model List<QuanLyThongTinBenBaiCho.Models.LichSu>
@{
    Layout = null;
    int index = 1;
}
<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th> Ngày đấu giá </th>
            <th> Giá trị (triệu đồng)</th>
            <th> Ngày bắt đầu </th>
            <th> Ngày kết thúc </th>
            <th> Tên đơn vị sử dụng </th>
            <th style="width:200px; min-width:100px;"> &nbsp; </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@index</td>
                <td>@item.NgayDauGia.ToShortDateString()</td>
                <td>@item.GiaTri</td>
                <td>@item.NgayBatDau.ToShortDateString()</td>
                <td>@item.NgayKetThuc.ToShortDateString()</td>
                <td>@item.TenDonVi</td>
                <td class="align-middle text-right">
                    @{
                        var uEdit = Url.Action("AddOrUpdate", "LichSu") + "/" + item.LichSuId;
                        var urlEdit = @"Popup('" + uEdit + "')";
                        var uDelete = Url.Action("Delete", "LichSu") + "/" + item.LichSuId;
                        var urluDelete = @"Delete('" + uDelete + "')";

                        index++;
                    }
                    <a href="#" onclick="@urlEdit" class="btn btn-sm btn-icon btn-secondary"><i class="fa fa-pencil-alt"></i> <span class="sr-only">Sửa</span></a>
                    <a href="#" onclick="@urluDelete" class="btn btn-sm btn-icon btn-secondary"><i class="far fa-trash-alt"></i> <span class="sr-only">Xóa</span></a>
                </td>
            </tr>
        }
    </tbody>
</table>